version: '3'

services:
  django_polls:
    container_name: polls_container
    build: ./django_polls
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_polls/:/app
    ports:
      - 8000:8000
    env_file:
      - env.dev
    depends_on:
      - db


  db:
    container_name: container_db
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.dev

volumes:
  postgres_data:
